name: Downloader

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Download File
        run: |
          curl -L "https://datanodes.to/g95lys4xlrqh/Wicked_Seed_--_fitgirl-repacks.site_--_.part01.rar" -o file.zip

      - name: Upload File
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-file
          path: file.zip
